POST {{base}}/anything/users
Authorization: Bearer {{token}}

{"name": "Viktor"}

> assert status == 200
> assert body.json.name == "Viktor"
> assert headers.content-type contains json
> assert duration < 5000
